<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class MemberSeeder extends Seeder
{
    public function run()
    {
        $data = [
            [
                'first_name' => 'Kobe',
                'last_name' => 'Bryant',
                'date_of_birth' => '1978-08-23',
                'license_number' => 'LA780824',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Michael',
                'last_name' => 'Jordan',
                'date_of_birth' => '1963-02-17',
                'license_number' => 'MI630217',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'LeBron',
                'last_name' => 'James',
                'date_of_birth' => '1984-12-30',
                'license_number' => 'LE841230',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Stephen',
                'last_name' => 'Curry',
                'date_of_birth' => '1988-03-14',
                'license_number' => 'ST880314',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Kevin',
                'last_name' => 'Durant',
                'date_of_birth' => '1988-09-29',
                'license_number' => 'KE880929',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Shaquille',
                'last_name' => 'O\'Neal',
                'date_of_birth' => '1972-03-06',
                'license_number' => 'SH720306',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Tim',
                'last_name' => 'Duncan',
                'date_of_birth' => '1976-04-25',
                'license_number' => 'TI760425',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Magic',
                'last_name' => 'Johnson',
                'date_of_birth' => '1959-08-14',
                'license_number' => 'MA590814',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Larry',
                'last_name' => 'Bird',
                'date_of_birth' => '1956-12-07',
                'license_number' => 'LA561207',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Kareem',
                'last_name' => 'Abdul-Jabbar',
                'date_of_birth' => '1947-04-16',
                'license_number' => 'KA470416',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Wilt',
                'last_name' => 'Chamberlain',
                'date_of_birth' => '1936-08-21',
                'license_number' => 'WI360821',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Bill',
                'last_name' => 'Russell',
                'date_of_birth' => '1934-02-12',
                'license_number' => 'BI340212',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Hakeem',
                'last_name' => 'Olajuwon',
                'date_of_birth' => '1963-01-21',
                'license_number' => 'HA630121',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Dirk',
                'last_name' => 'Nowitzki',
                'date_of_birth' => '1978-06-19',
                'license_number' => 'DI780619',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Giannis',
                'last_name' => 'Antetokounmpo',
                'date_of_birth' => '1994-12-06',
                'license_number' => 'GI941206',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Nikola',
                'last_name' => 'Jokic',
                'date_of_birth' => '1995-02-19',
                'license_number' => 'NI950219',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Luka',
                'last_name' => 'Doncic',
                'date_of_birth' => '1999-02-28',
                'license_number' => 'LU990228',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Allen',
                'last_name' => 'Iverson',
                'date_of_birth' => '1975-06-07',
                'license_number' => 'AL750607',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Charles',
                'last_name' => 'Barkley',
                'date_of_birth' => '1963-02-20',
                'license_number' => 'CH630220',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Scottie',
                'last_name' => 'Pippen',
                'date_of_birth' => '1965-09-25',
                'license_number' => 'SC650925',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Dwyane',
                'last_name' => 'Wade',
                'date_of_birth' => '1982-01-17',
                'license_number' => 'DW820117',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Kawhi',
                'last_name' => 'Leonard',
                'date_of_birth' => '1991-06-29',
                'license_number' => 'KA910629',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'James',
                'last_name' => 'Harden',
                'date_of_birth' => '1989-08-26',
                'license_number' => 'JA890826',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Chris',
                'last_name' => 'Paul',
                'date_of_birth' => '1985-05-06',
                'license_number' => 'CH850506',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Russell',
                'last_name' => 'Westbrook',
                'date_of_birth' => '1988-11-12',
                'license_number' => 'RU881112',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Anthony',
                'last_name' => 'Davis',
                'date_of_birth' => '1993-03-11',
                'license_number' => 'AN930311',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Damian',
                'last_name' => 'Lillard',
                'date_of_birth' => '1990-07-15',
                'license_number' => 'DA900715',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Kevin',
                'last_name' => 'Garnett',
                'date_of_birth' => '1976-05-19',
                'license_number' => 'KE760519',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Paul',
                'last_name' => 'Pierce',
                'date_of_birth' => '1977-10-13',
                'license_number' => 'PA771013',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Ray',
                'last_name' => 'Allen',
                'date_of_birth' => '1975-07-20',
                'license_number' => 'RA750720',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Clyde',
                'last_name' => 'Drexler',
                'date_of_birth' => '1962-06-22',
                'license_number' => 'CL620622',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Elgin',
                'last_name' => 'Baylor',
                'date_of_birth' => '1934-09-16',
                'license_number' => 'EL340916',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Oscar',
                'last_name' => 'Robertson',
                'date_of_birth' => '1938-11-24',
                'license_number' => 'OS381124',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Jerry',
                'last_name' => 'West',
                'date_of_birth' => '1938-05-28',
                'license_number' => 'JE380528',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'David',
                'last_name' => 'Robinson',
                'date_of_birth' => '1965-08-06',
                'license_number' => 'DA650806',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Karl',
                'last_name' => 'Malone',
                'date_of_birth' => '1963-07-24',
                'license_number' => 'KA630724',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'John',
                'last_name' => 'Stockton',
                'date_of_birth' => '1962-03-26',
                'license_number' => 'JO620326',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Isiah',
                'last_name' => 'Thomas',
                'date_of_birth' => '1961-04-30',
                'license_number' => 'IS610430',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Patrick',
                'last_name' => 'Ewing',
                'date_of_birth' => '1962-08-05',
                'license_number' => 'PA620805',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Steve',
                'last_name' => 'Nash',
                'date_of_birth' => '1974-02-07',
                'license_number' => 'ST740207',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Jason',
                'last_name' => 'Kidd',
                'date_of_birth' => '1973-03-23',
                'license_number' => 'JA730323',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Dirk',
                'last_name' => 'Nowitzki',
                'date_of_birth' => '1978-06-19',
                'license_number' => 'DI780619B',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Tracy',
                'last_name' => 'McGrady',
                'date_of_birth' => '1979-05-24',
                'license_number' => 'TR790524',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Vince',
                'last_name' => 'Carter',
                'date_of_birth' => '1977-01-26',
                'license_number' => 'VI770126',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Manu',
                'last_name' => 'Ginobili',
                'date_of_birth' => '1977-07-28',
                'license_number' => 'MA770728',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Tony',
                'last_name' => 'Parker',
                'date_of_birth' => '1982-05-17',
                'license_number' => 'TO820517',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Pau',
                'last_name' => 'Gasol',
                'date_of_birth' => '1980-07-06',
                'license_number' => 'PA800706',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Marc',
                'last_name' => 'Gasol',
                'date_of_birth' => '1985-01-29',
                'license_number' => 'MA850129',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Klay',
                'last_name' => 'Thompson',
                'date_of_birth' => '1990-02-08',
                'license_number' => 'KL900208',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Draymond',
                'last_name' => 'Green',
                'date_of_birth' => '1990-03-04',
                'license_number' => 'DR900304',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Jimmy',
                'last_name' => 'Butler',
                'date_of_birth' => '1989-09-14',
                'license_number' => 'JI890914',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Joel',
                'last_name' => 'Embiid',
                'date_of_birth' => '1994-03-16',
                'license_number' => 'JO940316',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Jayson',
                'last_name' => 'Tatum',
                'date_of_birth' => '1998-03-03',
                'license_number' => 'JA980303',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Kyrie',
                'last_name' => 'Irving',
                'date_of_birth' => '1992-03-23',
                'license_number' => 'KY920323',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Paul',
                'last_name' => 'George',
                'date_of_birth' => '1990-05-02',
                'license_number' => 'PA900502',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Dwight',
                'last_name' => 'Howard',
                'date_of_birth' => '1985-12-08',
                'license_number' => 'DW851208',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Carmelo',
                'last_name' => 'Anthony',
                'date_of_birth' => '1984-05-29',
                'license_number' => 'CA840529',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Reggie',
                'last_name' => 'Miller',
                'date_of_birth' => '1965-08-24',
                'license_number' => 'RE650824',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Grant',
                'last_name' => 'Hill',
                'date_of_birth' => '1972-10-05',
                'license_number' => 'GR721005',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Dennis',
                'last_name' => 'Rodman',
                'date_of_birth' => '1961-05-13',
                'license_number' => 'DE610513',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Alonzo',
                'last_name' => 'Mourning',
                'date_of_birth' => '1970-02-08',
                'license_number' => 'AL700208',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Kevin',
                'last_name' => 'McHale',
                'date_of_birth' => '1957-12-19',
                'license_number' => 'KE571219',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Robert',
                'last_name' => 'Parish',
                'date_of_birth' => '1953-08-30',
                'license_number' => 'RO530830',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'James',
                'last_name' => 'Worthy',
                'date_of_birth' => '1961-02-27',
                'license_number' => 'JA610227',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Chris',
                'last_name' => 'Webber',
                'date_of_birth' => '1973-03-01',
                'license_number' => 'CH730301',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Penny',
                'last_name' => 'Hardaway',
                'date_of_birth' => '1971-07-18',
                'license_number' => 'PE710718',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Gilbert',
                'last_name' => 'Arenas',
                'date_of_birth' => '1982-01-06',
                'license_number' => 'GI820106',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Amar\'e',
                'last_name' => 'Stoudemire',
                'date_of_birth' => '1982-11-16',
                'license_number' => 'AM821116',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Chris',
                'last_name' => 'Mullin',
                'date_of_birth' => '1963-07-30',
                'license_number' => 'CH630730',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Bernard',
                'last_name' => 'King',
                'date_of_birth' => '1956-12-04',
                'license_number' => 'BE561204',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Derrick',
                'last_name' => 'Rose',
                'date_of_birth' => '1988-10-04',
                'license_number' => 'DE881004',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Rajon',
                'last_name' => 'Rondo',
                'date_of_birth' => '1986-02-22',
                'license_number' => 'RA860222',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Kyle',
                'last_name' => 'Lowry',
                'date_of_birth' => '1986-03-25',
                'license_number' => 'KY860325',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Kobe',
                'last_name' => 'Bean',
                'date_of_birth' => '1978-08-23',
                'license_number' => 'KO780823B',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Stephen',
                'last_name' => 'Marbury',
                'date_of_birth' => '1977-02-20',
                'license_number' => 'ST770220',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Al',
                'last_name' => 'Horford',
                'date_of_birth' => '1986-06-03',
                'license_number' => 'AL860603',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'DeMarcus',
                'last_name' => 'Cousins',
                'date_of_birth' => '1990-08-13',
                'license_number' => 'DE900813',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Brandon',
                'last_name' => 'Roy',
                'date_of_birth' => '1984-07-23',
                'license_number' => 'BR840723',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Shawn',
                'last_name' => 'Kemp',
                'date_of_birth' => '1969-11-26',
                'license_number' => 'SH691126',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Khris',
                'last_name' => 'Middleton',
                'date_of_birth' => '1991-08-12',
                'license_number' => 'KH910812',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Anthony',
                'last_name' => 'Edwards',
                'date_of_birth' => '2001-08-05',
                'license_number' => 'AN010805',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Shai',
                'last_name' => 'Gilgeous-Alexander',
                'date_of_birth' => '1998-07-12',
                'license_number' => 'SH980712',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Ja',
                'last_name' => 'Morant',
                'date_of_birth' => '1999-08-10',
                'license_number' => 'JA990810',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Zion',
                'last_name' => 'Williamson',
                'date_of_birth' => '2000-07-06',
                'license_number' => 'ZI000706',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Devin',
                'last_name' => 'Booker',
                'date_of_birth' => '1996-10-30',
                'license_number' => 'DE961030',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Jamal',
                'last_name' => 'Murray',
                'date_of_birth' => '1997-02-23',
                'license_number' => 'JA970223',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Donovan',
                'last_name' => 'Mitchell',
                'date_of_birth' => '1996-09-07',
                'license_number' => 'DO960907',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Tyrese',
                'last_name' => 'Haliburton',
                'date_of_birth' => '2000-02-29',
                'license_number' => 'TY000229',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Chris',
                'last_name' => 'Bosh',
                'date_of_birth' => '1984-03-24',
                'license_number' => 'CH840324',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Blake',
                'last_name' => 'Griffin',
                'date_of_birth' => '1989-03-16',
                'license_number' => 'BL890316',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Yao',
                'last_name' => 'Ming',
                'date_of_birth' => '1980-09-12',
                'license_number' => 'YA800912',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Ben',
                'last_name' => 'Wallace',
                'date_of_birth' => '1974-09-10',
                'license_number' => 'BE740910',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Paul',
                'last_name' => 'Westphal',
                'date_of_birth' => '1950-11-30',
                'license_number' => 'PA501130',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Bob',
                'last_name' => 'McAdoo',
                'date_of_birth' => '1951-09-25',
                'license_number' => 'BO510925',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Dominique',
                'last_name' => 'Wilkins',
                'date_of_birth' => '1960-01-12',
                'license_number' => 'DO600112',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Kenny',
                'last_name' => 'Smith',
                'date_of_birth' => '1965-03-08',
                'license_number' => 'KE650308',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Peja',
                'last_name' => 'Stojakovic',
                'date_of_birth' => '1977-06-09',
                'license_number' => 'PE770609',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Chauncey',
                'last_name' => 'Billups',
                'date_of_birth' => '1976-09-25',
                'license_number' => 'CH760925',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Gary',
                'last_name' => 'Payton',
                'date_of_birth' => '1968-07-23',
                'license_number' => 'GA680723',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],
            [
                'first_name' => 'Latrell',
                'last_name' => 'Sprewell',
                'date_of_birth' => '1970-09-08',
                'license_number' => 'LA700908',
                'id_license_code'=>1,
                'license_status' => 1,
                'balance' => 0,
            ],

        ];

        $memberModel = model('MemberModel');

        foreach ($data as $member) {
            $memberModel->save($member);
        }
    }
}
